### PR TITLE
Disabled support

### PR DESCRIPTION
**Pull request by sroosen**
Added disabled state support. Fixes #17

### CODE REVIEW

**Comment by xpepermint** [comment]
@sroosen would you be so kind and also update the example so I can merge all together? Thanks.

**Comment by sroosen** [comment]
@xpepermint example has been updated

**Comment by mkeremguc** [comment]
bump

**Comment by mkeremguc** [comment]
thanks for merging. also bump the version for bower please

**Comment by xpepermint** [comment]
Done. Sorry guys for my late response.

**Comment by theraaz** [comment]
`disabled` works but not `ng-disabled`

**Pull request merged**
